export let DATA = [
  {
    createdAt: '2023-11-08T09:30:00Z',
    recipes: ['Pasta Carbonara', 'Ensalada César'],
    message:"Este es un comentario sobre una receta.",
    ingredients: ['Bacon', 'Huevos', 'Pasta', 'Lechuga', 'Pollo', 'Aderezo'],
  },
  {
    createdAt: '2023-10-15T14:45:00Z',
    recipes: ['Sopa de Verduras', 'Tarta de Manzana'],
    message:"Este es un comentario sobre una receta.",
    ingredients: [
      'Zanahorias',
      'Calabacín',
      'Cebolla',
      'Manzanas',
      'Harina',
      'Azúcar',
    ],
  },
  {
    createdAt: '2023-12-20T11:00:00Z',
    recipes: ['Filete de Salmón', 'Arroz Pilaf'],
    message:"Este es un comentario sobre una receta.",
    ingredients: [
      'Salmón',
      'Arroz',
      'Cebollino',
      'Mantequilla',
      'Caldo de Pollo',
    ],
  },
  {
    createdAt: '2023-09-05T08:15:00Z',
    recipes: ['Tacos de Pollo', 'Guacamole'],
    message:"Este es un comentario sobre una receta.",
    ingredients: [
      'Pollo',
      'Tortillas',
      'Aguacate',
      'Tomate',
      'Cilantro',
      'Cebolla',
    ],
  },
  {
    createdAt: '2023-08-12T17:20:00Z',
    recipes: ['Pizza Casera', 'Ensalada Mixta'],
    message:"Este es un comentario sobre una receta.",
    ingredients: [
      'Harina',
      'Levadura',
      'Tomate',
      'Queso',
      'Aceitunas',
      'Lechuga',
    ],
  },
  {
    createdAt: '2023-07-25T10:55:00Z',
    recipes: ['Sopa de Fideos', 'Pastel de Chocolate'],
    message:"Este es un comentario sobre una receta.",
    ingredients: [
      'Fideos',
      'Caldo de Pollo',
      'Chocolate',
      'Harina',
      'Huevos',
      'Leche',
    ],
  },
  {
    createdAt: '2023-06-18T15:00:00Z',
    recipes: ['Hamburguesas Caseras', 'Puré de Patatas'],
    message:"Este es un comentario sobre una receta.",
    ingredients: [
      'Carne Molida',
      'Pan de Hamburguesa',
      'Papas',
      'Mantequilla',
      'Leche',
    ],
  },
  {
    createdAt: '2023-11-30T12:00:00Z',
    recipes: [
      'Lasaña de Carne',
      'Ensalada de Frutas',
      'Pescado al Horno',
      'Risotto de Champiñones',
      'Tarta de Limón',
    ],
    message:"Este es un comentario sobre una receta.",
    ingredients: [
      'Carne molida',
      'Pasta para lasaña',
      'Tomate',
      'Queso',
      'Frutas variadas',
      'Filete de pescado',
      'Arroz',
      'Champiñones',
      'Limones',
      'Harina',
      'Azúcar',
    ],
  },
  {
    createdAt: '2023-04-10T09:30:00Z',
    recipes: ['Pollo al Curry', 'Ensalada de Quinoa'],
    message:"Este es un comentario sobre una receta.",
    ingredients: [
      'Pechugas de pollo',
      'Curry en polvo',
      'Quinoa',
      'Verduras mixtas',
      'Aceite de oliva',
    ],
  },
  {
    createdAt: '2023-02-20T16:45:00Z',
    recipes: ['Sushi Variado', 'Sopa Miso'],
    message:"Este es un comentario sobre una receta.",
    ingredients: [
      'Salmón fresco',
      'Arroz para sushi',
      'Algas nori',
      'Tofu',
      'Pasta de miso',
    ],
  },
  {
    createdAt: '2023-01-05T11:15:00Z',
    recipes: ['Pasta Alfredo', 'Ensalada Caprese'],
    message:"Este es un comentario sobre una receta.",
    ingredients: [
      'Pasta fettuccine',
      'Crema de leche',
      'Queso parmesano',
      'Tomates frescos',
      'Albahaca',
    ],
  },
  {
    createdAt: '2023-03-15T08:00:00Z',
    recipes: ['Huevos Benedictinos', 'Muffins de Arándanos'],
    message:"Este es un comentario sobre una receta.",
    ingredients: [
      'Huevos',
      'Jamón',
      'Pan inglés',
      'Arándanos frescos',
      'Harina de trigo',
    ],
  },
];
